---
title: "CCS_SupplementaryFig9_P1P2P4"
output: CCS_sfigure9
editor_options: 
  chunk_output_type: console
---
# Analysis
```{r}
Idents(ccs) <- ccs$dev.age
markers_cc_p1p2 <- FindMarkers(cc, 
                             ident.1 = 'P1', 
                             ident.2 = 'P2',
                             logfc.threshold = 0, 
                             only.pos = F)
markers_cc_p1p4 <- FindMarkers(cc, 
                             ident.1 = 'P1', 
                             ident.2 = 'P4',
                             logfc.threshold = 0, 
                             only.pos = F)
markers_cc_p2p4 <- FindMarkers(cc, 
                             ident.1 = 'P2', 
                             ident.2 = 'P4',
                             logfc.threshold = 0, 
                             only.pos = F)

markers_cc_p1p2p4 <- FindAllMarkers(cc,
                                logfc.threshold = 0, 
                                only.pos = F)

write.table(markers_cc_p1p2p4, file = "markers_cc_p1p2p4.txt", sep = '\t')
write.table(markers_cc_p1p2, file = "markers_cc_p1p2.txt", sep = '\t')
write.table(markers_cc_p1p4, file = "markers_cc_p1p4.txt", sep = '\t')
write.table(markers_cc_p2p4, file = "markers_cc_p2p4.txt", sep = '\t')

rm(markers_cc_p1p2, markers_cc_p2p4, markers_cc_p1p4, markers_cc_p1p2p4)
```


# Supp Figure 5A - DimPlot for P1/P2/P4
```{r}
fig <- DimPlot(ccs, 
        group.by = 'dev.age',  
        cols = c("#ffb700", "#ff4a00","#4871ff"), 
        pt.size = 0.8, 
        shuffle = T) &
  NoAxes() &
  theme(plot.title = element_blank(),
    legend.position = c(0.83, 0.75),
    #legend.position = c(0.87, 0.25),
        legend.key.size = unit(0.6,'cm'),
        legend.text = element_text(size = 12),
        plot.margin = unit(c(0,0,0,0), "cm"))

ggsave(fig,
       file = "sfig5a.tiff",
       dpi = 300, width = 5, height = 4)
```

# Supp Figure 5A - DimPlot for P1/P2/P4
```{r}
fig <- DimPlot(ccs, 
        split.by = 'dev.age',  
        cols = c("#ffb700", "#ff4a00","#4871ff"), 
        pt.size = 0.8, 
        shuffle = T) &
  NoAxes() &
  NoLegend()
  theme(plot.title = element_blank(),
        plot.margin = unit(c(0,0,0,0), "cm"))

ggsave(fig,
       file = "sfig5a_2.tiff",
       dpi = 300, width = 15, height = 4)
```

# Supp Figure 5C - DimPlot for P1/P2/P4_split
```{r}
DimPlot(
  ccs,
  pt.size = 1.4,
  shuffle = T,
  split.by  = 'dev.age',
  group.by = 'sub_all_onehis',
  cols = mycolors2
) &
  NoAxes() &
  theme(
    plot.title = element_blank(),
    legend.key.size = unit(1.5, 'line'),
    legend.text = element_text(size = 20, ),
    plot.margin = unit(c(0, 0, 0, 0), "cm")
  ) 
```

# Supp Figure 5B
```{r}
ggplot(cellpercent, aes(fill = Var2, y = Freq, x = Var1)) +
  geom_bar(position = "fill", stat = "identity") +
  scale_fill_manual(values = c("#ffb700", "#ff4a00", "#4871ff")) +
  xlab("") +
  ylab("Porportion") +
  theme(
    panel.background = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_text(
      color = 'black',
      size = 9,
      angle = 45,
      vjust = 1,
      hjust = 1
    ),
    axis.title.y = element_text(color = 'black', size = 10),
    axis.text.y = element_text(color = 'black', size = 8),
    legend.title = element_blank(),
    legend.text = element_text(size = 11),
    legend.key.size = unit(0.4, 'cm')
  )
```

# Supp Figure 5D
```{r}
cellpercent <- table(ccs$sub_all_onehis, ccs$dev.age)
cellpercent <- data.frame(cellpercent)

ggplot(cellpercent, aes(fill = Var1, y = Freq, x = Var2)) +
  geom_bar(position = "fill", stat = "identity") +
  scale_fill_manual(values = mycolors2) +
  xlab("") +
  ylab("Proportion") +
  theme(
    panel.background = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_text(color = 'black', size = 11),
    axis.title.y = element_text(color = 'black', size = 11),
    axis.text.y = element_text(color = 'black', size = 9),
    legend.title = element_blank(),
    legend.text = element_text(size = 9.5),
    legend.key.size = unit(0.45, 'cm')
  )
```


# sFigure 5E
```{r}
VlnPlot(
  ccs,
  features = c("Cpne5", "Hcn4", "Cacna2d2"),
  group.by = 'sub_all_onehis',
  stack = TRUE,
  split.by = 'dev.age',
  flip = T,
  cols = c("#ffb700", "#ff4a00", "#4871ff")
) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    #axis.text.x = element_text(size = 0, angle = 45, vjust = 1, hjust= 1),
    axis.ticks.length.x = unit(0.2, "cm"),
    axis.ticks.length.y = unit(0.1, "cm"),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size = 12),
    strip.text = element_text(size = 17, hjust = 0, face = "italic"),
    plot.margin = unit(c(0, 0, 0, 0), "cm")
  ) +
  NoLegend()


VlnPlot(
  ccs,
  features = c("Cpne5", "Hcn4", "Cacna2d2"),
  group.by = 'sub_all_onehis',
  stack = TRUE,
  split.by = 'dev.age',
  flip = T,
  cols = c("#ffb700", "#ff4a00", "#4871ff")
) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    #axis.text.x = element_text(size = 0, angle = 45, vjust = 1, hjust= 1),
    axis.ticks.length.x = unit(0.2, "cm"),
    axis.ticks.length.y = unit(0.1, "cm"),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size = 12),
    strip.text = element_text(size = 1)
  ) +
  NoLegend()
```

```{r}
VlnPlot(
  ccs,
  features = c("Myh6", "Myh7", "percent.mito"),
  group.by = 'sub_all_onehis',
  stack = TRUE,
  split.by = 'dev.age',
  flip = T,
  cols = c("#ffb700", "#ff4a00", "#4871ff")
) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.length.x = unit(0.2, "cm"),
    axis.ticks.length.y = unit(0.1, "cm"),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size = 12),
    strip.text = element_text(size = 17, hjust = 0, face = "italic"),
    plot.margin = unit(c(0, 0, 0, 0), "cm")
  ) +
  NoLegend()




VlnPlot(
  ccs,
  features = c("Myh6", "Myh7", "percent.mito"),
  group.by = 'sub_all_onehis',
  stack = TRUE,
  split.by = 'dev.age',
  flip = T,
  cols = c("#ffb700", "#ff4a00", "#4871ff")
) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    #axis.text.x = element_text(size = 0, angle = 45, vjust = 1, hjust= 1),
    axis.ticks.length.x = unit(0.2, "cm"),
    axis.ticks.length.y = unit(0.1, "cm"),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size = 12),
    strip.text = element_text(size = 1)
  ) +
  NoLegend()

```


```{r}
VlnPlot(
  ccs,
  features = c("Nppb", "Kcne1", "Atcayos"),
  group.by = 'sub_all_onehis',
  stack = TRUE,
  split.by = 'dev.age',
  flip = T,
  cols = c("#ffb700", "#ff4a00", "#4871ff")
) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    #axis.text.x = element_text(size = 0, angle = 45, vjust = 1, hjust= 1),
    axis.ticks.length.x = unit(0.2, "cm"),
    axis.ticks.length.y = unit(0.1, "cm"),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size = 12),
    strip.text = element_text(size = 17, hjust = 0, face = "italic")
  ) +
  NoLegend()



VlnPlot(
  ccs,
  features = c("Nppb", "Kcne1", "Atcayos"),
  group.by = 'sub_all_onehis',
  stack = TRUE,
  split.by = 'dev.age',
  flip = T,
  cols = c("#ffb700", "#ff4a00", "#4871ff")
) &
  
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    #axis.text.x = element_text(size = 0, angle = 45, vjust = 1, hjust= 1),
    axis.ticks.length.x = unit(0.2, "cm"),
    axis.ticks.length.y = unit(0.1, "cm"),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size = 12),
    strip.text = element_text(size = 1)
  ) +
  NoLegend()
```

# sfig5efg
```{r}
VlnPlot(
  ccs,
  features = c(
    "Tdtomato",
    "Cntn2",
    "Cpne5",
    "Myh6",
    "Myh7",
    "percent.mito",
    "Nppb",
    "Kcne1",
    "Atcayos"
  ),
  fill.by = 'ident',
  stack = TRUE,
  split.by = 'dev.age',
  group.by = 'sub_all_onehis',
  flip = T,
  cols = c("#ffb700", "#ff4a00", "#4871ff")
) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_text(size = 10),
    axis.ticks.length.x = unit(0.2, "cm"),
    axis.ticks.length.y = unit(0.1, "cm"),
    axis.title.y = element_text(size = 18),
    axis.text.y = element_text(size = 15),
    strip.text = element_text(size = 21, hjust = 0, face = "italic")
  ) +
  NoLegend()
```
