---
title: "CCS_SupplementaryFig8_ProlifCCS"
output: html_document
date: "2024-01-15"
editor_options: 
  chunk_output_type: console
---

```{r}
subset_prolif <- subset(ccs, idents = "Proliferative CCS")
subset_prolif <- NormalizeData(subset_prolif)
subset_prolif <- FindVariableFeatures(subset_prolif)
subset_prolif <- ScaleData(subset_prolif, vars.to.regress = c('nCount_RNA', 'percent.mito'))
subset_prolif <- RunPCA(subset_prolif)
ElbowPlot(subset_prolif, ndims = 50)
```

# Find appropriate clusters for lnb-pbb
```{r}
subset_prolif <- RunUMAP(subset_prolif, dims = 1:20)
subset_prolif <- FindNeighbors(subset_prolif, dims = 1:20)
subset_prolif <- FindClusters(subset_prolif, resolution = 0.6)
DimPlot(subset_prolif) & NoAxes()
```

# Assign cell cycle scores
```{r}
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes

s.genes <- str_to_title(s.genes)
g2m.genes <- str_to_title(g2m.genes)

subset_prolif <-
  CellCycleScoring(
    subset_prolif,
    s.features = s.genes,
    g2m.features = g2m.genes,
    set.ident = TRUE
  )

```

# Sfiga - Heatmap
```{r}
DoHeatmap(
  ccs,
  features = c(s.genes, g2m.genes),
  draw.lines = TRUE,
  lines.width = 10,
  label = FALSE,
  disp.min = -2,
  disp.max = 2,
  group.bar.height = 0.02,
  group.colors = mycolors2
) &
  NoLegend() &
  # scale_fill_gradientn(colors = c("navy", "white", "red")) &
  theme(
    legend.key.size = unit(0.5, 'cm'),
    legend.position = "right",
    legend.title = element_blank(),
    legend.text = element_text(size = 7),
    legend.box.just = "center",
    legend.box = "vertical",
    axis.text.y = element_text(size = 5, face = 'italic')
  )
```

# sFigxb - UMAP - clusters
```{r}
DimPlot(subset_prolif,
        group.by = "seurat_clusters",
        pt.size = 1.4) &
  NoAxes() &
  theme(
    text = element_text(size = 12),
    plot.title = element_blank(),
    panel.background = element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill = "transparent", colour = NA)
  )
```


# UMAP - developmental stage
```{r}
DimPlot(
  subset_prolif,
  group.by = "dev.age",
  cols =  c("#ffb700", "#ff4a00", "#4871ff"),
  pt.size = 1.4
) &
  NoAxes() &
  theme(
    text = element_text(size = 12),
    plot.title = element_blank(),
    panel.background = element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill = "transparent", colour = NA)
  )
```

# UMAP - cellcycle
```{r}
DimPlot(
  subset_prolif,
  group.by = "Phase",
  cols =  c("#F58024", "#589c48", "#733381"),
  pt.size = 1.4
) &
  NoAxes() &
  theme(
    text = element_text(size = 12),
    plot.title = element_blank(),
    panel.background = element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill = "transparent", colour = NA)
  )
```


# Supp Figure 5D
```{r}
cellpercent_prolif <-
  table(subset_prolif$dev.age, subset_prolif$seurat_clusters)
cellpercent_prolif <- data.frame(cellpercent_prolif)

ggplot(cellpercent_prolif, aes(fill = Var1, y = Freq, x = Var2)) +
  geom_bar(position = "fill", stat = "identity") +
  scale_fill_manual(values = c("#ffb700", "#ff4a00", "#4871ff")) +
  xlab("") +
  ylab("Proportion") +
  theme(
    panel.background = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_text(
      color = 'black',
      size = 13,
      angle = 30,
      hjust = 1,
      vjust = 1
    ),
    axis.title.y = element_text(color = 'black', size = 11),
    axis.text.y = element_text(color = 'black', size = 9),
    axis.line = element_line(colour = 'black'),
    legend.title = element_blank(),
    legend.text = element_text(size = 9.5),
    legend.key.size = unit(0.45, 'cm')
  )

```

# Supp Figure 5F
```{r}
cellpercent_prolif <-
  table(subset_prolif$Phase, subset_prolif$seurat_clusters)
cellpercent_prolif <- data.frame(cellpercent_prolif)

ggplot(cellpercent_prolif, aes(fill = Var1, y = Freq, x = Var2)) +
  geom_bar(position = "fill", stat = "identity") +
  scale_fill_manual(values = c("#F58024", "#589c48", "#733381")) +
  xlab("") +
  ylab("Proportion") +
  theme(
    panel.background = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_text(
      color = 'black',
      size = 13,
      angle = 30,
      hjust = 1,
      vjust = 1
    ),
    axis.title.y = element_text(color = 'black', size = 11),
    axis.text.y = element_text(color = 'black', size = 9),
    axis.line = element_line(colour = 'black'),
    legend.title = element_blank(),
    legend.text = element_text(size = 9.5),
    legend.key.size = unit(0.45, 'cm')
  )
```

# FeaturePlots & VlnPlots of top genes per cluster
```{r}
FeaturePlot(
  subset_prolif,
  features = c("Mcm4", "Mcm5" , "Cdkn3",
               "Ccnb2", "Fam83d", "Cdc25b"),
  cols = c('lightgrey', 'red'),
  pt.size = 1,
  #min.cutoff = 'q3',
  ncol = 2,
  order = F
) &
  NoAxes() &
  theme(
    plot.title = element_text(size = 12, face = "italic"),
    legend.text = element_text(size = 8),
    legend.key.width = unit(0.25, 'cm'),
    legend.key.height = unit(0.25, 'cm'),
    legend.spacing.x = unit(0.12, 'cm')
  )


VlnPlot(
  subset_prolif,
  features = c("Mcm4", "Mcm5" , "Cdkn3",
               "Ccnb2", "Fam83d", "Cdc25b"),
  ncol = 2,
  pt.size = 0
) &
  #scale_x_discrete(labels = c("Cluster 1", "Cluster 2", "Cluster 3")) &
  theme(
    plot.title = element_text(size = 5, face = "italic"),
    axis.title.x = element_blank(),
    axis.text.x = element_text(
      size = 10,
      angle = 40,
      vjust = 1,
      hjust = 1
    ),
    axis.title.y = element_text(size = 9),
    axis.text.y = element_text(size = 7)
  ) &
  NoLegend()
```


