---
title: "CCS_MainFig5"
output: html_document
date: "2023-11-30"
---

# load libraries and data
```{r}
library(Seurat)
library(dplyr)
library(tidyverse)
library(tidyr)
library(ggplot2)
library(pheatmap)
library(igraph)

ccs <- readRDS('20231212_ccs_object.rds')
```

# filter only activating regulons to run AUCell
```{r}

#load pySCENIC output
reg <- read.csv('ccs_reg_10kb_500bp_min10pct_repress_mingenes5.csv')

#clean dataframe so it matches format required for pySCENIC
reg <- rbind(colnames(reg), reg)
reg[reg == "X"] <- ""
reg[reg == "X.1"] <- ""
reg[reg == "Enrichment.1"] <- "Enrichment"
reg[reg == "Enrichment.2"] <- "Enrichment"
reg[reg == "Enrichment.3"] <- "Enrichment"
reg[reg == "Enrichment.4"] <- "Enrichment"
reg[reg == "Enrichment.5"] <- "Enrichment"
reg[reg == "Enrichment.6"] <- "Enrichment"
reg[reg == "Enrichment.7"] <- "Enrichment"

#remove repressing regulons
reg <- reg[!grepl("repressing", reg$Enrichment.5), ]

#export as csv
write.table(reg, 
            "ccs_reg_10kb_500bp_min10pct_repress_mingenes5_activatingonly.csv", 
            row.names = F, 
            col.names = F, 
            sep=",")

```

# rank & filter TFs and generate activity matrix/heatmap (n_regions x n_regulons)
```{r}

auc_mtx <- read.csv('ccs_10kb_500bp_min10pct_repress_mingenes5_activatingonly_aucmtx.csv', row.names=1)

# clean colnames and replace periods with dashes to match gene expression matrix
colnames(auc_mtx) <- sub("\\.{3}$", "", colnames(auc_mtx))
colnames(auc_mtx) <- sub("\\.", "-", colnames(auc_mtx))

# load RSS (regulon-specificity score) matrix
rss <- read.csv('ccs_10kb_500bp_min10pct_repress_mingenes5_activatingonly_rss_sub_all_onehis.csv', row.names = 1)

# clean colnames and replace periods with dashes to match gene expression matrix
colnames(rss) <- sub("\\.{3}$", "", colnames(rss))
colnames(rss) <- sub("\\.", "-", colnames(rss))

# get top TFs per region by regulon-specificity score

sel <- apply(rss, 1, function(row) {
  
  sorted_tf_indices <- order(as.numeric(row), decreasing = TRUE)
  top_tf_indices <- sorted_tf_indices[1:min(length(sorted_tf_indices), 191)]
  top_tfs <- colnames(rss)[top_tf_indices]
  
  return(top_tfs)
  
})

#filter putative regulon TFs for each region by percent expression (40%)

sel <- as.data.frame(sel)

pctexpression <- readxl::read_xlsx('20231201_pctcellexpression.xlsx')
rownames(pctexpression) <- pctexpression$Marker

san_tfs <- sel$`SA node`
san_tfs <- san_tfs[pctexpression[san_tfs, "SA node"] >= 0.4]

avn_tfs <- sel$`Compact AV node`
avn_tfs <- avn_tfs[pctexpression[avn_tfs, "Compact AV node"] >= 0.4]

lnb_tfs <- sel$`Lower nodal bundle`
lnb_tfs <- lnb_tfs[pctexpression[lnb_tfs, "Lower nodal bundle"] >= 0.4]

his_tfs <- sel$`His bundle`
his_tfs <- his_tfs[pctexpression[his_tfs, "His bundle"] >= 0.4]

pbb_tfs <- sel$`Proximal bundle branch`
pbb_tfs <- pbb_tfs[pctexpression[pbb_tfs, "Proximal bundle branch"] >= 0.4]

dbb_tfs <- sel$`Distal bundle branch`
dbb_tfs <- dbb_tfs[pctexpression[dbb_tfs, "Distal bundle branch"] >= 0.4]

purkinje_tfs <- sel$`Purkinje fibers`
purkinje_tfs <- purkinje_tfs[pctexpression[purkinje_tfs, "Purkinje fibers"] >= 0.4]

contractile_tfs <- sel$`Contractile myocytes`
contractile_tfs <- contractile_tfs[pctexpression[contractile_tfs, "Contractile myocytes"] >= 0.4]

sel_regulons <- unique(c(san_tfs, avn_tfs, lnb_tfs, his_tfs, pbb_tfs, dbb_tfs, purkinje_tfs, contractile_tfs))

# subset AUC matrix to only include filtered regulons
auc_subset <- auc_mtx[,colnames(auc_mtx) %in% sel_regulons]

# generate matrix of mean regulon AUC in each region (n_regions x n_regulons)
auc_subset <- auc_subset %>% group_by(ccs@meta.data$sub_all_onehis)
mean_auc_subset <- auc_subset %>%
  summarise(across(everything(), ~mean(.[`ccs@meta.data$sub_all_onehis` %in% c("SA node", "AV node", "Lower nodal bundle", "His bundle", "Proximal bundle branch", "Distal bundle branch", "Purkinje fibers", "Contractile cardiomyocytes", "Proliferative CCS")])))
mean_auc_subset$`ccs@meta.data$sub_all_onehis` <- NULL
rownames(mean_auc_subset) <- levels(ccs@meta.data$sub_all_onehis)

# proliferative CCS excluded
mean_auc_subset <- mean_auc_subset[!(rownames(mean_auc_subset) == "Proliferative CCS"), ]
rownames(mean_auc_subset) <-
  c(
    "SA node",
    "AV node",
    "Lower nodal bundle",
    "His bundle",
    "Proximal bundle branch",
    "Distal bundle branch",
    "Purkinje fibers",
    "Contractile cardiomyocytes"
  )

# plot heatmap
pheatmap(
  mean_auc_subset,
  scale = 'column',
  cluster_rows = F,
  angle_col = 90,
  color = colorRampPalette(c('#576bc0', '#FFFFFF', '#ca2837'))(50)
)

# export file
write.csv(mean_auc_subset, 'mean_auc_subset.csv')
```

# dot plots
```{r}

# dotplot by average expression

# create pseudobulk expression matrix and convert to long format (tidyr)
pseudobulk_expmat <- AverageExpression(ccs, features=sel_regulons)
pseudobulk_expmat_df <- as.data.frame(pseudobulk_expmat)
pseudobulk_expmat_df$gene <- rownames(pseudobulk_expmat_df)
pseudobulk_expmat_long <- pivot_longer(pseudobulk_expmat_df, cols=-gene, names_to="region", values_to="avg_exp")

# clean names and exclude proliferative CCS
pseudobulk_expmat_long$region <- gsub("RNA\\.", "", pseudobulk_expmat_long$region)
pseudobulk_expmat_long$region <- gsub("\\.", " ", pseudobulk_expmat_long$region)
pseudobulk_expmat_long <- pseudobulk_expmat_long %>% filter(region != "Proliferative CCS")

#order by distal -> proximal -> nodes
pseudobulk_expmat_long$region <-
  factor(
    pseudobulk_expmat_long$region,
    levels = c(
      'Contractile myocytes',
      'Purkinje fibers',
      'Distal bundle branch',
      'Proximal bundle branch',
      'His bundle',
      'Lower nodal bundle',
      'Compact AV node',
      'SA node'
    )
  )

#order TFs as clustered by heatmap
pseudobulk_expmat_long$gene <- factor(pseudobulk_expmat_long$gene, levels = c("Irx2", "Tcf7l2", "Crem", "Zfp467", "Prrx2", "Mxd4", "Srebf2", "Cux1", "Mitf", "Etv1", "Mafb", "Thra", "Nfic", "Pura", "Max", "Nfia", "Mef2d", "Mxi1", "Nfe2l1", "Zfp148", "Prox1", "Zeb1", "Elf1", "Tfdp2", "Tbx5", "Atf3", "Jund", "Klf9", "Klf10", "Fos", "Jun", "Cebpb", "Sox4", "Bptf", "Zbtb7a", "Clock", "Hif1a", "Elf2", "Yy1", "Maff", "Mafg", "Rel", "Nfib", "Zbtb20", "Fosb", "Irf1", "Klf13", "Cebpd", "Junb", "Ctcf", "Egr1", "Hes1", "Vezf1", "Dbp", "Stat3", "Nr3c1", "Rest", "Mef2a", "Tead1", "Bhlhe40", "Ets2", "Zfp704", "Mlx", "Tcf4", "Gtf3a", "Hmg20b", "Esrra", "Irx4", "Mef2c", "Zfp560", "E2f6", "Usf1", "Gata6", "Nfix", "Atf5", "Shox2", "Nr2f1", "Nr2f2", "Klf4", "Rara", "Klf6", "Klf2", "Nfil3", "Tbx3", "Creb5", "Sp3", "Gata4", "Klf7", "Ddit3", "Xbp1", "Bach1", "Atf1", "Plagl1", "Nr1d1", "Nfyc", "Atf4", "Zfp131"))

#plot
ggplot(pseudobulk_expmat_long %>% group_by(gene) %>% mutate(avg_exp = scale(x=log1p(avg_exp))), aes(x = gene, y = region, size = avg_exp)) +
  geom_point() + 
  scale_size(range=c(0,3)) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle=90), 
        panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())


DotPlot(ccs, 
        features=c("Irx2", "Tcf7l2", "Crem", "Zfp467", "Prrx2", "Mxd4", "Srebf2", "Cux1", "Mitf", "Etv1", "Mafb", "Thra", "Nfic", "Pura", "Max", "Nfia", "Mef2d", "Mxi1", "Nfe2l1", "Zfp148", "Prox1", "Zeb1", "Elf1", "Tfdp2", "Tbx5", "Atf3", "Jund", "Klf9", "Klf10", "Fos", "Jun", "Cebpb", "Sox4", "Bptf", "Zbtb7a", "Clock", "Hif1a", "Elf2", "Yy1", "Maff", "Mafg", "Rel", "Nfib", "Zbtb20", "Fosb", "Irf1", "Klf13", "Cebpd", "Junb", "Ctcf", "Egr1", "Hes1", "Vezf1", "Dbp", "Stat3", "Nr3c1", "Rest", "Mef2a", "Tead1", "Bhlhe40", "Ets2", "Zfp704", "Mlx", "Tcf4", "Gtf3a", "Hmg20b", "Esrra", "Irx4", "Mef2c", "Zfp560", "E2f6", "Usf1", "Gata6", "Nfix", "Atf5", "Shox2", "Nr2f1", "Nr2f2", "Klf4", "Rara", "Klf6", "Klf2", "Nfil3", "Tbx3", "Creb5", "Sp3", "Gata4", "Klf7", "Ddit3", "Xbp1", "Bach1", "Atf1", "Plagl1", "Nr1d1", "Nfyc", "Atf4", "Zfp131"), 
        cols = c("#312E2E", "#312E2E"), 
        idents = c(
          'Contractile myocytes',
          'Purkinje fibers',
          'Distal bundle branch',
          'Proximal bundle branch',
          'His bundle',
          'Lower nodal bundle',
          'Compact AV node',
          'SA node'
        ), 
        dot.scale = 3) & 
  theme(axis.text.x = element_blank()) & 
  NoAxes()
```

# network plots
```{r}
mark <- FindAllMarkers(ccs, only.pos = T)

# regulator TFs: top 5 by RSS after filtering for 40% expression in respective region
# target genes: p_val_adj < 0.05 in respective region
```

# create adjacency list
```{r}
san_links <- read.csv('san_targets.csv')
san_links <- san_links[,1:2]
san_links <- inner_join(san_links, mark, by = c('target' = 'gene'))
san_links <- san_links %>% filter(p_val_adj < 0.05, cluster == 'SA node')
san_links <- san_links[,1:2]

# create graph
san_network <- graph_from_data_frame(d=san_links, directed=T)

# adjust node size of TFs (12) and targets (8)
V(san_network)$size <- 8
V(san_network)$size[V(san_network)$name %in% c("Nr2f2", "Shox2", "Nr2f1", "Tbx3", "Rara")] <- 12

# adjust node colour based on class
V(san_network)$colour <- "white"
V(san_network)$colour[V(san_network)$name %in% ion_channels] <- "#f08080"
V(san_network)$colour[V(san_network)$name %in% sarcomeres] <- "#b8b8ff"
V(san_network)$colour[V(san_network)$name %in% tf_list] <- "#7DF28B"
V(san_network)$colour[V(san_network)$name %in% c("Nr2f2", "Shox2", "Nr2f1", "Tbx3", "Rara")] <- "#D6D6D6"


tiff("~/san_network.tiff", width = , height = 7, units = "in", res = 500)

plot(san_network, 
     edge.arrow.size=0.1, 
     vertex.color=V(san_network)$colour, 
     vertex.label.family="sans",
     vertex.label.color="black", 
     vertex.size=V(san_network)$size, 
     vertex.label.cex=V(san_network)$size/26, 
     vertex.label.font=2, 
     layout=layout_with_fr(san_network))

dev.off()
```

# Plot cAVN network
```{r}
avn_links <- read.csv('avn_targets.csv')
avn_links <- avn_links[,1:2]
avn_links <- inner_join(avn_links, mark, by = c('target' = 'gene'))
avn_links <- avn_links %>% filter(p_val_adj < 0.05, cluster == 'AV node')
avn_links <- avn_links[,1:2]

avn_network <- graph_from_data_frame(d=avn_links, directed=T)

V(avn_network)$size <- 8
V(avn_network)$size[V(avn_network)$name %in% c("Tbx3", "Nr1d1", "Gata6", "Klf7", "Creb5")] <- 12

V(avn_network)$colour <- "white"
V(avn_network)$colour[V(avn_network)$name %in% ion_channels] <- "#f08080"
V(avn_network)$colour[V(avn_network)$name %in% sarcomeres] <- "#b8b8ff"
V(avn_network)$colour[V(avn_network)$name %in% tf_list] <- "#7DF28B"
V(avn_network)$colour[V(avn_network)$name %in% c("Tbx3", "Nr1d1", "Gata6", "Klf7", "Creb5")] <- "#D6D6D6"


tiff("~/avn_network.tiff", width = 6, height = 6, units = "in", res = 500)

plot(avn_network, 
     edge.arrow.size=0.1, 
     vertex.color=V(avn_network)$colour, 
     vertex.label.family="sans", 
     vertex.label.color="black", 
     vertex.size=V(avn_network)$size, 
     vertex.label.cex=V(avn_network)$size/26, 
     vertex.label.font=2, 
     layout=layout_with_fr(avn_network),
     margin = c(0,0,0,0))

dev.off()
```


```{r}
his_links <- read.csv('his_targets.csv')
his_links <- his_links[,1:2]
his_links <- inner_join(his_links, mark, by = c('target' = 'gene'))
his_links <- his_links %>% filter(p_val_adj < 0.05, cluster == 'His bundle')
his_links <- his_links[,1:2]

his_network <- graph_from_data_frame(d=his_links, directed=T)

V(his_network)$size <- 8
V(his_network)$size[V(his_network)$name %in% c("Tbx3", "Tcf4", "Gata4", "Creb5", "Bhlhe40")] <- 12

V(his_network)$colour <- "white"
V(his_network)$colour[V(his_network)$name %in% ion_channels] <- "#f08080"
V(his_network)$colour[V(his_network)$name %in% sarcomeres] <- "#b8b8ff"
V(his_network)$colour[V(his_network)$name %in% tf_list] <- "#7DF28B"
V(his_network)$colour[V(his_network)$name %in% c("Tbx3", "Tcf4", "Gata4", "Creb5", "Bhlhe40")] <- "#D6D6D6"


tiff("~his_network.tiff", width = 6, height = 6, units = "in", res = 500)

plot(his_network, 
     edge.arrow.size=0.1, 
     vertex.color=V(his_network)$colour, 
     vertex.label.family="sans", 
     vertex.label.color="black", 
     vertex.size=V(his_network)$size, 
     vertex.label.cex=V(his_network)$size/26, 
     vertex.label.font=2, 
     layout=layout_with_fr(his_network))

dev.off()
```


```{r}
purkinje_links <- read.csv('purkinje_targets.csv')
purkinje_links <- purkinje_links[,1:2]
purkinje_links <- inner_join(purkinje_links, mark, by = c('target' = 'gene'))
purkinje_links <- purkinje_links %>% filter(p_val_adj < 0.05, cluster == 'Purkinje fibers')
purkinje_links <- purkinje_links[,1:2]

purkinje_network <- graph_from_data_frame(d=purkinje_links, directed=T)

V(purkinje_network)$size <- 8
V(purkinje_network)$size[V(purkinje_network)$name %in% c("Srebf2", "Max", "Mafb", "Etv1", "Thra")] <- 12

V(purkinje_network)$colour <- "white"
V(purkinje_network)$colour[V(purkinje_network)$name %in% ion_channels] <- "#f08080"
V(purkinje_network)$colour[V(purkinje_network)$name %in% sarcomeres] <- "#b8b8ff"
V(purkinje_network)$colour[V(purkinje_network)$name %in% tf_list] <- "#7DF28B"
V(purkinje_network)$colour[V(purkinje_network)$name %in% c("Srebf2", "Max", "Mafb", "Etv1", "Thra")] <- "#D6D6D6"


tiff("~/pf_network.tiff", width = 6, height = 6, units = "in", res = 500)
plot(purkinje_network, 
     edge.arrow.size=0.1, 
     vertex.color=V(purkinje_network)$colour, 
     vertex.label.family="sans", 
     vertex.label.color="black", 
     vertex.size=V(purkinje_network)$size, 
     vertex.label.cex=V(purkinje_network)$size/26, 
     vertex.label.font=2, 
     layout=layout_with_fr(purkinje_network))

dev.off()
```