---
title: "CCS_SupplementaryFig7_cAVN-LNB-HIS"
output: html_document
date: "2023-12-19"
editor_options: 
  chunk_output_type: console
---

# sFig7 - Difference between AVN/LNB/His - DotPlot (with all ccs groups)
```{r}
DotPlot(
  ccs,
  features = c("Hcn4", "Cpne5", "Tbx3", "Irx3", "Etv1", "Gjd3", "Gja5", "Gja1",  "Myl4", "Myl7","Myl2", "Myl3" ),
  idents = c("Compact AV node", "Lower nodal bundle", "His bundle", "Contractile myocytes"),
  cols = c('whitesmoke', 'deeppink4'),
  col.min = -1,
  col.max = 1,
  dot.scale = 10,
  #dot.min = -0.10
)  &
  guides(color = guide_colorbar(title = 'Average\nExpression')) &
  guides(size = guide_legend(title = 'Percent\nExpressed')) &
  RotatedAxis() &
  scale_size(breaks = c(0, 25, 50, 75, 100)) &
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(
      size = 12,
      angle = 90,
      vjust = 0.5,
      hjust = 0.5
    ),
    axis.ticks.length.x.bottom = unit(3, 'mm'),
    axis.text.y = ggtext::element_markdown(size = 14,
                                          colour = c("#BBBBBB",  "#F6C141","#F1932D", "#E8601C")),
    legend.position = "right",
    legend.direction = "vertical",
    legend.box = "vertical",
    legend.title = element_blank(),
    legend.text = element_text(size = 9),
    legend.key.width = unit(0.4, 'cm'),
    legend.key.height = unit(0.4, 'cm')
  )
```


# sFigx - Difference between AVN/LNB/His - Heatmap for spatial
```{r}
spatial_avnlnbhis_allgroups <- read.table("~/spatial_avnlnbhiscc.txt")
row.names(spatial_avnlnbhis_allgroups) <- spatial_avnlnbhis_allgroups$V1
spatial_avnlnbhis_allgroups$V1 <- NULL
```

# Create labels
```{r}
spatialheatmap_labels <- read.table("~/q3_ExpressionFile_wlnb_forfig2_heatmap_groups.txt")
colnames(spatial_avnlnbhis_allgroups) <- spatialheatmap_labels[3:7,20,22] # avn-lnb-his
colnames(spatial_avnlnbhis_allgroups) <-c(spatialheatmap_labels[3:7], spatialheatmap_labels[20], spatialheatmap_labels[22]) # avn-lnb-his-cc
colnames(spatial_avnlnbhis_allgroups) <- spatialheatmap_labels[1:19] # all ccs
colnames(spatial_avnlnbhis_allgroups) <- spatialheatmap_labels # all groups
```

# Scale data
```{r}
spatial_avnlnbhis_allgroups_scaled <- as.matrix(t(scale(t(spatial_avnlnbhis_allgroups))))
spatial_avnlnbhis_allgroups_scaled <- t(spatial_avnlnbhis_allgroups_scaled)
```

# Color palette - blue
```{r}
colorRampPalette(brewer.pal(9,"Blues"))(100)
heatmap_spatial_col = circlize::colorRamp2(c(-2, 0, 2), c("#F7FBFF", "#6DAFD6", "#08306B")) # used for FC>1.2, pval<0.05
```

# Fig2A - Spatial heatmap - AVN/LNB/HIS
```{r}
tiff("~/spatial_avnlnbhiscc.tiff", width = 3.1, height = 1.8, units = "in", res = 500)

fig <- Heatmap(
  spatial_avnlnbhis_allgroups_scaled,
  name = "Scaled\nExpression",
  cluster_columns = FALSE,
  cluster_rows = FALSE,
  show_row_dend = FALSE,
  col = heatmap_spatial_col,
  use_raster = FALSE,
  row_names_gp = gpar(fontsize = 6),
  row_names_side = 'left',
  column_names_gp = gpar(fontsize = 6),
  column_names_side = 'top'
)

draw(fig)

dev.off()
```


# sFigx - Difference between AVN/LNB/His - Heatmap for spatial - AVERAGE
```{r}
spatial_avnlnbhis_allgroups <-
  read.table(
    "~/spatial_average_avnlnbhiscc.txt"
  )
row.names(spatial_avnlnbhis_allgroups) <-
  spatial_avnlnbhis_allgroups$V1
spatial_avnlnbhis_allgroups$V1 <- NULL
```

# Create labels
```{r}
spatialheatmap_labels <- read.table("~/spatial_groups_average.txt")
colnames(spatial_avnlnbhis_allgroups) <- spatialheatmap_labels[3:7,20,22] # avn-lnb-his
colnames(spatial_avnlnbhis_allgroups) <- c(spatialheatmap_labels[3:7], spatialheatmap_labels[20], spatialheatmap_labels[22]) # avn-lnb-his-cc
colnames(spatial_avnlnbhis_allgroups) <- spatialheatmap_labels[1:19] # all ccs
colnames(spatial_avnlnbhis_allgroups) <- spatialheatmap_labels # all groups
colnames(spatial_avnlnbhis_allgroups) <- c(spatialheatmap_labels[2:4], spatialheatmap_labels[11], spatialheatmap_labels[13]) # all groups
```

# Scale data
```{r}
spatial_avnlnbhis_allgroups_scaled <- as.matrix(t(scale(t(spatial_avnlnbhis_allgroups))))
spatial_avnlnbhis_allgroups_scaled <- t(spatial_avnlnbhis_allgroups_scaled)
```

# Color palette - blue
```{r}
colorRampPalette(brewer.pal(9,"Blues"))(100)
heatmap_spatial_col = circlize::colorRamp2(c(-2, 0, 2), c("#F7FBFF", "#6DAFD6", "#08306B")) # used for FC>1.2, pval<0.05
```

# sFig7 - Spatial heatmap - AVN/LNB/HIS
```{r}
tiff("~/spatial_average_avnlnbhiscc.tiff", width = 3.1, height = 1.3, units = "in", res = 500)

fig <- Heatmap(
  spatial_avnlnbhis_allgroups_scaled,
  name = "Scaled\nExpression",
  cluster_columns = FALSE,
  cluster_rows = FALSE,
  show_row_dend = FALSE,
  col = heatmap_spatial_col,
  use_raster = FALSE,
  row_names_gp = gpar(fontsize = 6),
  row_names_side = 'left',
  column_names_gp = gpar(fontsize = 6),
  column_names_side = 'top'
)

draw(fig)

dev.off()
```